### ISSUE TITLE
Getting an error 500 trying to update the record

### ISSUE THREAD

**Issue by cyberpower678** [workerforce/unifi-ddns#49]
2024-01-21T23:43:08-05:00 Dream-Machine-Pro inadyn[41309]: [500 Internal Server Error] Error: Failed to update dns record
    at Cloudflare.updateRecord (index.js:50:13)
    at async informAPI (index.js:121:5)
    at async handleRequest (index.js:108:20)
2024-01-21T23:43:08-05:00 Dream-Machine-Pro inadyn[41309]: Will retry again in 600 sec ...

Not really sure where it's going wrong, aside from where in the JS it's throwing the error.  I've setup an API token exactly as described in the docs and copied that into the password field on my UDM, specified the host record to be updated and set the username as the root domain name.

**Comment by cyberpower678** [comment]
Nevermind, it just started working on its own.  Must have been a glitch.
